### ISSUE TITLE
issues with loading data files into Strudel 

### ISSUE THREAD

**Issue by biowackysci** [imilne/strudel#1]
Hello Everyone,
I am trying to load my dataset into strudel and it seems to be doing nothing. So I have formatted it in a txt file and have the extension as .strudel. Can someone please help me with it ?
I have attached a snippet of my table below
Feature	Ryegrass	7	ID_121787_scaffold5861_Locus_1631_1_65.1_COMPLEX_No_definition_line_found	SNP	8604.77
Feature	Ryegrass	7	ID_155916_Locus_15819_Contig1_No_definition_line_found	SNP	8947.63
Feature	Ryegrass	7	ID_147843_scaffold73433_Locus_63158_3_44.5_COMPLEX_No_definition_line_found	SNP	8958.24
Feature	Ryegrass	7	ID_136152_scaffold71086_Locus_59334_0_56.1_COMPLEX_No_definition_line_found	SNP	8967.51
Feature	Ryegrass	7	ID_135663_Locus_96044_Contig1_No_definition_line_found	SNP	9081.67
Feature	Ryegrass	7	ID_167250_Locus_31543_Contig1_No_definition_line_found	SNP	9113.39
Feature	Ryegrass	7	ID_167843_scaffold17513_Locus_5528_4_34.9_COMPLEX_No_definition_line_found	SNP	9148.8
Feature	Ryegrass	7	ID_146961_scaffold86065_Locus_90545_2_58.6_COMPLEX_No_definition_line_found	SNP	9519.98
homolog	Ryegrass	ID_162967_Locus_99311_Contig1_No_definition_line_found	Brachypodium	BRADI_1g00480v3	0
homolog	Ryegrass	ID_23248_C774726_63.0_No_definition_line_found	Brachypodium	BRADI_1g00700v3	2.11E-79
homolog	Ryegrass	ID_24591_C920359_80.0_No_definition_line_found	Brachypodium	BRADI_1g00700v3	1.97E-70
homolog	Ryegrass	ID_163001_scaffold82929_Locus_82836_0_29.5_FORK_No_definition_line_found	Brachypodium	BRADI_1g02170v3	0
homolog	Ryegrass	ID_139142_C1431526_58.0_No_definition_line_found	Brachypodium	BRADI_1g02310v3	0
homolog	Ryegrass	ID_153446_Locus_83327_Contig1_No_definition_line_found	Brachypodium	BRADI_1g02810v3	0
homolog	Ryegrass	ID_145280_scaffold99483_Locus_135397_2_41.4_COMPLEX_No_definition_line_found	Brachypodium	BRADI_1g02950v3	0
homolog	Ryegrass	ID_161281_scaffold46561_Locus_26996_4_47.4_COMPLEX_No_definition_line_found	Brachypodium	BRADI_1g03050v3	0
homolog	Ryegrass	ID_150436_scaffold72256_Locus_61163_1_52.0_COMPLEX_No_definition_line_found	Brachypodium	BRADI_1g03120v3	3.27E-176
homolog	Ryegrass	ID_148225_scaffold63970_Locus_48054_3_33.1_COMPLEX_No_definition_line_found	Brachypodium	BRADI_1g03130v3	9.21E-117
homolog	Ryegrass	ID_151237_Locus_7327_Contig1_No_definition_line_found	Brachypodium	BRADI_1g03170v3	0
homolog	Ryegrass	ID_154225_Locus_28162_Contig1_No_definition_line_found	Brachypodium	BRADI_1g03250v3	0

Is the right format ?
Thanks in advance for your help

**Comment by mb47** [comment]
Hi biowackysci, 
looking at your file snippet everything seems to be in order except for the fact that "Feature" starts with a capital F -- the parsing code is case sensitive and expects lower case. So if you change that to lower case it should work ok (unless there are other errors in your input file that don't appear in your snippet).
cheers
Micha

**Comment by biowackysci** [comment]
Thanks for your reply. Now hte problem seems to have drifted away from that into "Data load failed:java.io.IOException: Error reading line 64510. 5 Please correct your data and try again

![image](https://user-images.githubusercontent.com/44249260/58672753-c0367d00-838b-11e9-943e-0e68ac1f4dc1.png)


And here is what i have been uploading and the * ed line is the one causing trouble 

homolog	Ryegrass	48851	Rice	LOC_Os12g44310.1	3.56E-70
homolog	Ryegrass	158980	Rice	LOC_Os12g44380.1	0
homolog	Ryegrass	138819	Wheat	1A_10068070	0
*homolog	Ryegrass	159115	Wheat	1A_108077240 0
homolog	Ryegrass	24306	Wheat	1A_121129306 1.28E-58
homolog	Ryegrass	162133	Wheat	1A_130149250 0
homolog	Ryegrass	160252	Wheat	1A_133166538 0
homolog	Ryegrass	166043	Wheat	1A_13925743 1.63E-59
homolog	Ryegrass	158229	Wheat	1A_186989022 0
homolog	Ryegrass	145341	Wheat	1A_298621845	0
homolog	Ryegrass	161021	Wheat	1A_310248349	9.9E-140
homolog	Ryegrass	94671	Wheat	1A_323204834	1.59E-100

Can you please help me out here ?
Thanks again
Saila

**Comment by mb47** [comment]
Hi Saila,

I need some more information to troubleshoot/reproduce this. You could either post/send me your whole input file, or if this is not an option, you could send me the Strudel log which should contain more details on the error. On Windows you find this file here:

C:\Users\<username>\.scri-bioinf\strudel.log

A couple of suggestions for what might be causing this is a missing entry for the feature, a misspelled name for the feature, or unexpected/missing characters on that line (have a look at the input file in a plain text editor with control characters showing).

Micha

**Comment by biowackysci** [comment]
Hello Micha,
Thanks for your reply, but i figured out what the issue was. It was just that my feature and homolog entries that different position details which made a lot of sense why it would not see the entry valid. 
Thanks again so much for your help 
Saila
